import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://test-claimcenter.donegalgroup.com/cc/ClaimCenter.do');
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).fill('su');
  await page.getByRole('textbox', { name: 'User name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('D');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('Donegal2019');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.locator('a').filter({ hasText: /^Claim$/ }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('[id=":tabs-menu-trigger"]').click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Policy #' }).click();
  await page.locator('a').filter({ hasText: /^Claim$/ }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Claim #' }).click({
    modifiers: ['ControlOrMeta']
  });
  await page.getByRole('textbox', { name: 'Policy #' }).click();
  await page.getByRole('textbox', { name: 'Claim #' }).fill('http://test-claimcenter.donegalgroup.com');
  await page.getByRole('textbox', { name: 'Policy #' }).click();
  await page.getByRole('textbox', { name: 'Claim #' }).click();
  await page.getByRole('textbox', { name: 'Policy #' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Claim #' }).dblclick();
  await page.getByRole('textbox', { name: 'Claim #' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Claim #' }).fill('');
  await page.getByRole('textbox', { name: 'Policy #' }).click();
  await page.getByRole('textbox', { name: 'Claim #' }).fill('1002241425');
  await page.getByRole('textbox', { name: 'Policy #' }).click();
  await page.getByRole('textbox', { name: 'Policy #' }).fill('1002241425');
  await page.getByRole('textbox', { name: 'Claim #' }).click();
  await page.getByRole('textbox', { name: 'Claim #' }).fill('');
  await page.getByRole('link', { name: 'Search' }).click();
  await page.locator('#header-2534').click();
  await page.locator('a').filter({ hasText: /^Claim$/ }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CXL-DE-01-26-0747169)' }).click();
  await page.locator('[id=":TabLinkMenuButton"]').click();
  await page.getByRole('menuitem', { name: 'Log Out Super User' }).click();
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).fill('benjsmit');
  await page.getByRole('textbox', { name: 'User name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('gw');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('D');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('Donegal2019');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.locator('a').filter({ hasText: /^Claim$/ }).click();
  await page.locator('a').filter({ hasText: 'Claim (CPP-TX-90-26-0747163)' }).click();
  await page.locator('a').filter({ hasText: 'Claim (CPP-TX-90-26-0747163)' }).click();
  await page.locator('[id="Claim:ClaimMenuActions"]').click();
  await page.getByRole('menuitem', { name: 'Choose by Coverage' }).click();
  await page.getByRole('menuitem', { name: 'Inside the Premises - Theft' }).click();
  await page.getByRole('combobox', { name: 'Loss Party' }).click();
  await page.getByRole('option', { name: 'Insured\'s loss' }).click();
  await page.getByRole('combobox', { name: 'Cause of Loss' }).click();
  await page.getByRole('option', { name: 'All Other Losses Not' }).click();
  await page.getByRole('combobox', { name: 'Cause of Loss Description' }).click();
  await page.getByRole('option', { name: 'All Other' }).click();
  await page.getByRole('combobox', { name: 'Coverage Denied?' }).click();
  await page.getByRole('option', { name: 'No', exact: true }).click();
  await page.getByRole('combobox', { name: 'Coverage Location' }).click();
  await page.getByRole('option', { name: '3 : Commercial Crime Location' }).click();
  await page.getByRole('combobox', { name: 'Claimant' }).click();
  await page.getByRole('option', { name: 'Blessed Bubbles LLC' }).click();
  await page.getByRole('combobox', { name: 'Type' }).click();
  await page.getByRole('option', { name: 'Insured', exact: true }).click();
  await page.getByRole('combobox', { name: 'Damaged/Stolen Item:' }).click();
  await page.getByRole('textbox', { name: 'Property Description' }).click();
  await page.getByRole('textbox', { name: 'Property Description' }).fill('totally ddamaged due to wind');
  await page.getByRole('textbox', { name: 'Damage Description' }).click();
  await page.getByRole('textbox', { name: 'Damage Description' }).fill('fbfbvc');
  await page.locator('[id="NewExposure:NewExposureScreen:Update"]').click();
  await page.getByRole('row', { name: '1 Inland Marine or Crime' }).getByRole('img').click();
  await page.locator('[id="Claim:ClaimMenuActions"]').click();
  await page.getByRole('menuitem', { name: 'Assign Claim' }).click();
  await page.getByRole('combobox', { name: 'Select from list:' }).click();
  await page.getByRole('option', { name: 'Justin York (Bodily Injury' }).click();
  await page.locator('[id="AssignClaimsPopup:AssignmentPopupScreen:AssignmentPopupDV:AssignmentPopupScreen_ButtonButton"]').click();
  await page.locator('[id="ClaimExposures:ClaimExposuresScreen:ClaimExposures_CloseExposure"]').click();
  await page.locator('[id="CloseExposurePopup:CloseExposureScreen:Cancel"]').click();
  await page.getByRole('row', { name: '1 Inland Marine or Crime' }).getByRole('img').click();
  await page.locator('[id="ClaimExposures:ClaimExposuresScreen:ClaimExposures_CreateReserve"]').click();
  await page.getByText('-').nth(4).click();
  await page.locator('#textfield-1935-inputEl').fill('050000');
  await page.locator('#centerPanel').click();
  await page.getByText('<none>').click();
  await page.getByRole('option', { name: 'New Loss' }).click();
  await page.locator('[id="NewReserveSet:NewReserveSetScreen:Update"]').click();
  await page.locator('[id="Claim:ClaimMenuActions"]').click();
  await page.getByRole('menuitem', { name: 'New Payment (Formerly System' }).click();
  await page.getByRole('combobox', { name: 'Name' }).click();
  await page.getByRole('option', { name: 'Blessed Bubbles LLC' }).click();
  await page.locator('[id="NormalCreateCheckWizard:Next"]').click();
  await page.getByRole('combobox', { name: 'Reserve Line' }).click();
  await page.locator('#ext-element-747').click();
  await page.locator('#textfield-2297-inputEl').fill('5000');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('textbox', { name: 'Total Amount of Check' }).fill('500');
});